name: aoa
favicon: null
layout_spectrum: 0.6659302501939237
typography_spectrum: 0.6364159705117345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7199549553915858
  lightness: 0.6966319887433201
  saturation: 0.3424130252096802
  rhythmicContrast: 0.7939488526899368
purpose: []
