name: aoa
favicon: null
layout_spectrum: 0.6659302501939237
typography_spectrum: 0.22662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#a5a5a5'
    - '#4c4c4c'
    - '#c8c8c8'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
